package com.practice.parsing;

public class ParsingData_JSON {
	public static String newData() {
		return "{\r\n"
				+ "  \"squadName\": \"Super hero squad\",\r\n"
				+ "  \"homeTown\": \"Metro City\",\r\n"
				+ "  \"formed\": 2016,\r\n"
				+ "  \"secretBase\": \"Super tower\",\r\n"
				+ "  \"active\": true,\r\n"
				+ "  \"members\": [\r\n"
				+ "    {\r\n"
				+ "      \"name\": \"Molecule Man\",\r\n"
				+ "      \"age\": 29,\r\n"
				+ "      \"secretIdentity\": \"Dan Jukes\",\r\n"
				+ "      \"powers\": [\r\n"
				+ "        \"Radiation resistance\",\r\n"
				+ "        \"Turning tiny\",\r\n"
				+ "        \"Radiation blast\"\r\n"
				+ "      ]\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "      \"name\": \"Madame Uppercut\",\r\n"
				+ "      \"age\": 39,\r\n"
				+ "      \"secretIdentity\": \"Jane Wilson\",\r\n"
				+ "      \"powers\": [\r\n"
				+ "        \"Million tonne punch\",\r\n"
				+ "        \"Damage resistance\",\r\n"
				+ "        \"Superhuman reflexes\"\r\n"
				+ "      ]\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "      \"name\": \"Eternal Flame\",\r\n"
				+ "      \"age\": 1000000,\r\n"
				+ "      \"secretIdentity\": \"Unknown\",\r\n"
				+ "      \"powers\": [\r\n"
				+ "        \"Immortality\",\r\n"
				+ "        \"Heat Immunity\",\r\n"
				+ "        \"Inferno\",\r\n"
				+ "        \"Teleportation\",\r\n"
				+ "        \"Interdimensional travel\"\r\n"
				+ "      ]\r\n"
				+ "    }\r\n"
				+ "  ]\r\n"
				+ "}\r\n"
				+ "";
	}

}
